### ISSUE TITLE
Code syntax highlighting works only with markdown not restructured text

### ISSUE THREAD

**Issue by dnene** [sQu4rks/crowsfoot#1]
The .rst files generate a different set of classes (not codehilite) for which the code highlighting has not been configured to work

**Comment by porterjamesj** [comment]
hmmm interesting; I prefer markdown which probably explains why I haven't caught this. Will take a look as soon as I can.

**Comment by dnene** [comment]
I did a few enhancements here. https://github.com/dnene/crowsfoot/commits/master Though the changes for the .rst support are most certainly a bad dream for a good css author https://github.com/dnene/crowsfoot/commit/1e287db670f1ab861cc18ca6a71919cda9cfe304 . I suck at HTML / CSS but it should tell you the changes I had to make. This post http://blog.dhananjaynene.com/2013/09/screencast-overview-of-python-enums-pep-435/ uses a .rst source file.

Also added stuff for supporting atom feeds, disqus integration, and google analytics. Though did them in a bit of hurry, would be happy to review and offer the slightly refined versions as pull requests.

**Comment by porterjamesj** [comment]
yeah that would be great!

I threw this together in a hurry for myself and just put it up on pelican-themes because I liked the design. Making it more usable for others who use more pelican features than me would be super appreciated :+1:

**Comment by dnene** [comment]
Ok. Will submit a pull request for all but the code highlighting for .rst features over the next 2-3 days. Will wait for you to appropriately decide whats the right way to deal with it and then merge downstream (as I said earlier - I really do not know the details or work with CSS that frequently enough to work out an appropriate solution)

Will submit the following as 3 pull requests. 
- Using Atom feeds instead of RSS feeds
- Disqus integration
- Adding google analytics.
